[build]
builder = "nixpacks"
buildCommand = "npm run install-server"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && node index.js"
restartPolicyType = "on_failure"
healthcheckPath = "/"
